//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValerioWeb.UI.Commercial {
    
    
    public partial class FormulaireLivraison {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ValerioWeb.UI.Commercial.Commercial Master {
            get {
                return ((ValerioWeb.UI.Commercial.Commercial)(base.Master));
            }
        }
    }
}
